project:
  type: website
  output-dir: docs

website:
  title: "Zane Sano Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual